package de.draegerit.serialcommander.view;

public enum EHelp {
	SETTINGS_PORT, SETTINGS_BAUDRATE, SETTINGS_DATABITS, SETTINGS_PARITY, SETTINGS_STOPBITS, TAB_TITEL, LOGFILE_NAME, LOGFILE_AKTIVE

}
